name = "1.20.1"
author = "Starlight"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d4618c38103fe61798912c7aab839b0c4fa810b60ea34d370fb4935c828ddfa"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
