name = "1.20.1"
author = "Starlight"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "096d8e93adc5b0b5b43b34e7a127936a60e2a7aae902acaea604f007ed1f4707"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
